INSERT INTO positions(position_name)
VALUES
('UNIVERSITY_PROFESSOR'),
('PROFESSOR'),
('ASSOCIATE_PROFESSOR'),
('ASSISTANT_PROFESSOR'),
('MASTER_INSTRUCTOR'),
('SENIOR_INSTRUCTOR'),
('INSTRUCTOR'),
('RESEARCH_ASSOCIATE'),
('ADJUNCT_PROFESSOR');